trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  registry: $(DockerServiceConnection)
  # set this to your repository name
  repository: starter-laravel9

steps:
  - task: Docker@2
    displayName: Login to registry
    inputs:
      command: login
      containerRegistry: $(registry)
  - task: Docker@2
    displayName: Build and push
    inputs:
      command: buildAndPush
      repository: $(repository)
      dockerfile: Dockerfile
      tags: latest
