version: '3'

services:
  mailcatcher:
    image: syncloudsoftech/mailcatcher
    ports:
      - '1025:1025'
      - '8025:8025'

  minio:
    image: minio/minio:latest
    command: minio server /data/minio --address ":9090" --console-address ":9091"
    environment:
      MINIO_ROOT_USER: starterapp
      MINIO_ROOT_PASSWORD: starterapp
    ports:
      - '9090:9090'
      - '9091:9091'
    volumes:
      - minio-data:/data/minio

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: starterapp
      MYSQL_USER: starterapp
      MYSQL_PASSWORD: starterapp
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: starterapp
      PMA_PASSWORD: starterapp
    ports:
      - '8080:80'

  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8081:8081'

volumes:
  minio-data:
  mysql-data:
  redis-data:
